### PR TITLE
VEOSS-1923 initial return correction value endpoint and call

### PR DESCRIPTION
**Pull request by DevAndyroo**

### CODE REVIEW

**Review by susan-badel — APPROVED** [review]

**Comment by DevAndyroo** [comment]
retest this please

**Comment by DevAndyroo** [comment]
retest this please

**Comment by DevAndyroo** [comment]
retest this please

**Review by Lee-Powell — APPROVED** [review]

**Comment by DevAndyroo** [comment]
retest this please

**Review by susan-badel — APPROVED** [review]

**Comment by DevAndyroo** [comment]
retest this please

**Pull request merged**
